### ISSUE TITLE
use `asdf` local dependencies when running install

### ISSUE THREAD

**Issue by lifeiscontent** [MetricMike/asdf-awscli#6]
**Describe the bug**

I tried to do an asdf install awscli latest and got an error relating to python not being installed.

I have a version of python installed via `asdf install python latest` I think `asdf-awscli` should be smart enough to use local dependencies when running an install.

**Steps to reproduce**

install local version of python into a folder
install awscli and watch it fail (must remove global versions of python)

**Expected behavior**

awscli should install

**Screenshots**

**Additional context**

**Comment by MetricMike** [comment]
Hello,

Unfortunately I need more information from you to determine what's going wrong here.

`asdf install awscli latest` will grab the latest v2 version, which comes with a vendor-ed python that ignores your local dependencies (this is intentional for v2 of awscli). This process is outlined in https://github.com/MetricMike/asdf-awscli/blob/main/lib/utils.bash#L64-L100.

Unless you're using Windows (which has some weirdness described in #2 and isn't actively tested yet), I'm not quite sure what you're seeing. Could you run the following commands and post the output here?

`python --version`
`which python`
`asdf info`
`aws --version`
`which aws`

For v1, this plugin relies on a working python3 installation available on the ${PATH} which is the only supported installation method by the awscli tool itself.

**Comment by lifeiscontent** [comment]
@MetricMike I see, I was hoping v1 could use a python version locally, but if its baked into the installer then we can close this issue. Might be worth pointing that out in the readme.

**Comment by MetricMike** [comment]
V1 is using a local python version available on ${PATH}. The README explicitly calls out a dependency on a python available on PATH
